---
language: bash
services: docker

dist: trusty

env:
  - VERSION=jessie VARIANT=9.6
  - VERSION=jessie.slim VARIANT=9.6


before_script:
  - cd ${VERSION}-${VARIANT}
  - image="saxix/python:$VERSION${VARIANT:+-${VARIANT}}"
  - env | sort

script:
  - mkdir ./data
  - docker build --pull -t "$image" .
  - docker run -it -e POSTGRES_DB=test -v $PWD/data:/var/lib/postgresql/${VARIANT}/main -v $PWD/tests:/tests $image /bin/bash -c "cd /tests && /tests/runtests.sh"
